#!/bin/bash
set -e

# Starts the unit tests
node bin/stackio --config bin/test/seed.json &
node bin/test/service/app.js &

./node_modules/nodeunit/bin/nodeunit bin/test/server/udp.js

pushd bin/test/static
python -m SimpleHTTPServer &
popd

echo "Test server running. Please navigate your browser to http://localhost:8000."

#Called when the user control+c's, to close background processes
function control_c {
    kill `jobs -p`
    exit $?
}

trap control_c SIGINT
while true; do read x; done
