#!/bin/sh

function utils {
    python bin/registrar/app.py &
    python bin/authorizer/app.py bin/apps/seed.json &
    sleep 1s
}

function server {
    node bin/server-app/app &
}

function dashboard {
    utils; server
    node bin/apps/dashboard/server/app.js &

    pushd bin/apps/dashboard/static
    python -m SimpleHTTPServer &
    popd
}

function test {
    utils; server
    node bin/apps/test/server/app.js &
    
    pushd bin/apps/test/static
    python -m SimpleHTTPServer &
    popd
}

function meece {
    utils; server
    node bin/apps/meece/server/app.js &
    
    pushd bin/apps/meece/static
    python -m SimpleHTTPServer &
    popd
}

function oauth {
    utils; server
    node bin/apps/oauth/server/app.js &
    
    pushd bin/apps/oauth/static
    python -m SimpleHTTPServer &
    popd
}

function control_c {
    kill `jobs -p`
    exit $?
}

for i in $@
do
    $i
done

trap control_c SIGINT
while true; do read x; done