#!/bin/sh

# Starts the registrar and authorizer
function utils {
    node bin/registrar/standalone.js &
    node bin/authorizer/sqlite/standalone.js bin/apps/seed.json --dbname bin/authorizer/sqlite/authorizer.db &
    sleep 1s
}

# Starts a server using OAuth authentication
function server_oauth {
    node bin/server-app/oauth-app &
}

# Starts a server using normal authentication
function server_normalauth {
    node bin/server-app/normalauth-app &
}

# Starts a dashboard
function dashboard {
    utils; server_normalauth
    node bin/apps/dashboard/server/app.js &

    pushd bin/apps/dashboard/static
    python -m SimpleHTTPServer &
    popd
}

# Starts the unit tests
function test {
    utils; server_normalauth
    node bin/apps/test/server/app.js &
    
    pushd bin/apps/test/static
    python -m SimpleHTTPServer &
    popd
}

# Starts the mice app
function mice {
    utils; server_normalauth
    node bin/apps/mice/server/app.js &
    
    pushd bin/apps/mice/static
    python -m SimpleHTTPServer &
    popd
}

# Starts the OAuth test app
function oauth {
    utils; server_oauth
    node bin/apps/oauth/server/app.js &
    
    pushd bin/apps/oauth/static
    python -m SimpleHTTPServer &
    popd
}

# Starts the stress tester
function stress {
    utils; server_normalauth
    node bin/apps/stress/server/app.js &
    
    pushd bin/apps/stress/static
    python -m SimpleHTTPServer &
    popd
}

#Called when the user control+c's, to close background processes
function control_c {
    kill `jobs -p`
    exit $?
}

for i in $@
do
    $i
done

trap control_c SIGINT
while true; do read x; done
